# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PictureMode.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore
from PyQt5.QtCore import Qt, QSize
from qfluentwidgets import FluentIcon as FIF


class Ui_PictureMode(object):
    def setupUi(self, PictureMode):
        PictureMode.setObjectName("PictureMode")
        PictureMode.resize(960, 810)
        self.picture_show = HorizontalFlipView(PictureMode)
        self.picture_show.setGeometry(QtCore.QRect(20, 60, 675, 675))
        self.picture_show.setObjectName("picture_show")
        self.picture_show.setAspectRatioMode(Qt.AspectRatioMode.KeepAspectRatio)
        self.picture_show.setItemSize(QSize(675, 675))
        self.picture_show.setFixedSize(QSize(675, 675))
        self.Slider_2 = Slider(PictureMode)
        self.Slider_2.setGeometry(QtCore.QRect(800, 430, 200, 161))
        self.Slider_2.setObjectName("Slider_2")
        self.Slider = Slider(PictureMode)
        self.Slider.setGeometry(QtCore.QRect(800, 160, 200, 141))
        self.Slider.setObjectName("Slider")
        self.SubtitleLabel = SubtitleLabel(PictureMode)
        self.SubtitleLabel.setGeometry(QtCore.QRect(780, 100, 131, 51))
        # self.SubtitleLabel.setTextFormat(QtCore.Qt.AutoText)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.SubtitleLabel_2 = SubtitleLabel(PictureMode)
        self.SubtitleLabel_2.setGeometry(QtCore.QRect(760, 360, 141, 51))
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.choose_one = PrimaryPushButton(FIF.PHOTO, "选择图片", self)
        self.choose_one.setGeometry(QtCore.QRect(780, 620, 131, 51))
        self.choose_one.setObjectName("choose_one")
        self.choose_all = PrimaryPushButton(FIF.FOLDER, "选择文件夹", self)
        self.choose_all.setGeometry(QtCore.QRect(780, 680, 131, 51))
        self.choose_all.setObjectName("choose_all")
        # self.InfoBadge = InfoBadge(PictureMode)
        # self.InfoBadge.setGeometry(QtCore.QRect(260, 370, 241, 51))
        # self.InfoBadge.setObjectName("InfoBadge")

        self.retranslateUi(PictureMode)
        QtCore.QMetaObject.connectSlotsByName(PictureMode)

    def retranslateUi(self, PictureMode):
        _translate = QtCore.QCoreApplication.translate
        PictureMode.setWindowTitle(_translate("PictureMode", "PictureMode"))
        self.SubtitleLabel.setText(_translate("PictureMode", "置信度"))
        self.SubtitleLabel_2.setText(_translate("PictureMode", "非极大抑制"))

from qfluentwidgets import HorizontalFlipView, PrimaryPushButton, Slider, SubtitleLabel,InfoBadge
