# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'VideoMode.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore
from qfluentwidgets import FluentIcon as FIF
from PyQt5.QtWidgets import QWidget, QVBoxLayout
from qfluentwidgets.multimedia import VideoWidget


class Ui_VideoMode(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 810)
        Form.setMinimumSize(QtCore.QSize(0, 0))
        self.Slider = Slider(Form)
        self.Slider.setGeometry(QtCore.QRect(800, 160, 200, 141))
        self.Slider.setObjectName("Slider")
        self.SubtitleLabel_2 = SubtitleLabel(Form)
        self.SubtitleLabel_2.setGeometry(QtCore.QRect(760, 360, 141, 51))
        self.SubtitleLabel_2.setObjectName("SubtitleLabel_2")
        self.SubtitleLabel = SubtitleLabel(Form)
        self.SubtitleLabel.setGeometry(QtCore.QRect(780, 100, 131, 51))

        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.choose_all = PrimaryPushButton(FIF.ACCEPT, "确定", self)
        self.choose_all.setGeometry(QtCore.QRect(780, 680, 131, 51))
        self.choose_all.setObjectName("choose_all")
        self.Slider_2 = Slider(Form)
        self.Slider_2.setGeometry(QtCore.QRect(800, 430, 200, 161))
        self.Slider_2.setObjectName("Slider_2")
        self.choose_video = PrimaryPushButton(FIF.VIDEO, "选择视频", self)
        self.choose_video.setGeometry(QtCore.QRect(780, 620, 131, 51))
        self.choose_video.setObjectName("choose_video")
        # self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        # self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 80, 691, 661))
        # self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        # self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        # self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        # self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(30, 70, 675, 675))
        self.widget.setObjectName("widget")
        self.vBoxLayout = QVBoxLayout(self.widget)
        self.videoWidget = VideoWidget(self.widget)
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SubtitleLabel_2.setText(_translate("Form", "非极大抑制"))
        self.SubtitleLabel.setText(_translate("Form", "置信度"))

from qfluentwidgets import PrimaryPushButton, Slider, SubtitleLabel
